version: "3.9"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /mnt/sonarr:/config
      - /mnt/media:/media
    environment:
      TZ: "Europe/Berlin"
      PUID: 1000
      PGID: 1000
    ports:
      - 8989:8989
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - /mnt/radarr:/config
      - /mnt/media:/media
    environment:
      TZ: "Europe/Berlin"
      PUID: 1000
      PGID: 1000
    ports:
      - 7878:7878
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    volumes:
      - /mnt/sabnzbd:/config
      - /mnt/media:/media
    environment:
      TZ: "Europe/Berlin"
      PUID: 1000
      PGID: 1000
    ports:
      - 8080:8080
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /mnt/jellyfin:/config
      - /mnt/media:/media
    ports:
      - 8096:8096
