version: "3.9"

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: IfNotStopped
    volumes:
      - /mnt/sonarr:/config
      - /mnt/media:/media
    environment:
      TZ: "Europe/Berlin"
      PUID: 1000
      PGID: 1000
    ports:
      - 8989:8989
